### 1. sklearn.preprocessing.LabelEncoder
_class_ sklearn.preprocessing.LabelEncoder[[source]](https://github.com/scikit-learn/scikit-learn/blob/ff1023fda/sklearn/preprocessing/_label.py#L36)[](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder "Permalink to this definition")

In [11]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

LE = LabelEncoder()
LE.fit(items)
labels = LE.transform(items)
print('인코딩 변환값', labels)

인코딩 변환값 [0 1 4 5 3 3 2 2]


### 2. sklearn.preprocessing.OneHotEncoder
_class_ sklearn.preprocessing.OneHotEncoder(_*_,  _categories='auto'_,  _drop=None_,  _sparse='deprecated'_,  _sparse_output=True_,  _dtype=<class  'numpy.float64'>_,  _handle_unknown='error'_,  _min_frequency=None_,  _max_categories=None_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/ff1023fda/sklearn/preprocessing/_encoders.py#L215)[](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder "Permalink to this definition")

In [12]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
ohe = OneHotEncoder(max_categories=3, sparse=False).fit(X)
ohe.infrequent_categories_

C:\Users\Hong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


[array(['a', 'd'], dtype=object)]

In [5]:
ohe.transform([["a"], ["b"]])

array([[0., 0., 1.],
       [1., 0., 0.]])

In [22]:
from sklearn.preprocessing import OneHotEncoder

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환합니다.
labels = labels.reshape(-1,1)

# 원-핫 인코딩을 적용합니다.
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [37]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
items = np.array(items)
print(items)


items = np.array(items).reshape(-1,1)
print(items)

oh_encoder = OneHotEncoder(sparse=False)
result = oh_encoder.fit_transform(items)

['TV' '냉장고' '전자렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']
[['TV']
 ['냉장고']
 ['전자렌지']
 ['컴퓨터']
 ['선풍기']
 ['선풍기']
 ['믹서']
 ['믹서']]


C:\Users\Hong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [35]:
result

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [30]:
import pandas as pd

In [32]:
pd.DataFrame(result, columns= ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '믹서'])

TV  냉장고  전자렌지  컴퓨터  선풍기   믹서
0  1.0  0.0   0.0  0.0  0.0  0.0
1  0.0  1.0   0.0  0.0  0.0  0.0
2  0.0  0.0   0.0  0.0  1.0  0.0
3  0.0  0.0   0.0  0.0  0.0  1.0
4  0.0  0.0   0.0  1.0  0.0  0.0
5  0.0  0.0   0.0  1.0  0.0  0.0
6  0.0  0.0   1.0  0.0  0.0  0.0
7  0.0  0.0   1.0  0.0  0.0  0.0