### sklearn.preprocessing.PolynomialFeatures
_class_ sklearn.preprocessing.PolynomialFeatures(_degree=2_,  _*_,  _interaction_only=False_,  _include_bias=True_,  _order='C'_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/preprocessing/_polynomial.py#L30)[](https://scikit-learn.org/1.1/modules/generated/sklearn.preprocessing.PolynomialFeatures.html?highlight=poly#sklearn.preprocessing.PolynomialFeatures "Permalink to this definition")

In [7]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# 다항식으로 변환한 단항식 생성, [[0, 1], [2, 3]]의 2X2 행렬 생성
X = np.arange(4).reshape(2, 2)
print('1차 단항식 계수 feature: \n', X)

1차 단항식 계수 feature: 
 [[0 1]
 [2 3]]


In [8]:
# degree = 2 인 2차 다항식으로 변환하기 위해 PolynomialFeatures를 이용하여 변환
poly = PolynomialFeatures(degree=2)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 2차 다항식 계수 feature: \n', poly_ftr)

변환된 2차 다항식 계수 feature: 
 [[1. 0. 1. 0. 0. 1.]
 [1. 2. 3. 4. 6. 9.]]


In [9]:
def polynomial_func(X):
    y = 1 + 2*X + X**2 + X **3
    return y

X = np.arange(4).reshape(2, 2)
print('1차 단항식 계수 feature: \n', X)
y = polynomial_func(X)
print('3차 다항식 결정값: \n', y)

1차 단항식 계수 feature: 
 [[0 1]
 [2 3]]
3차 다항식 결정값: 
 [[ 1  5]
 [17 43]]


In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                 ('linear', LinearRegression())])

X = np.arange(4).reshape(2, 2)
y = polynomial_func(X)

model = model.fit(X, y)
print('Polynomial 회귀 계수\n', np.round(model.named_steps['linear'].coef_, 2))

Polynomial 회귀 계수
 [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]
